# =============================================
# Build config
# =============================================

root:             dist
dest:             <%= site.root %>
assets:           <%= site.dest %>/assets

# Data
data:             data/*.{json,yml}

# Templates
templates:        templates
includes:         <%= site.templates %>/includes/*.hbs
layouts:          <%= site.templates %>/layouts
layout:           default.hbs

# Extensions
helpers:
  - <%= site.templates %>/helpers/*.js

# =============================================
# Site metadata
# =============================================

title:            "The Butcher's Market in Dalton, GA"
description:      "Fresh meats cut by hand with old fashioned service in Dalton, GA; from our cutting block to your dinner table; featuring Black Angus Beef, Boar's Head Deli Products, Amish Wedding Foods"
keywords:         "butcher shop, meat, grocery store, meat market, groceries, grocers retail, meat markets, butcher shops, supermarkets, food stores, butchering, deli, angus beef, fresh meats, boar's head, meat packages, ground beef, salads, ham, turkey, steaks, pork chops, chicken, produce, fine wines, recipes, dalton, north georgia, party platters, party trays, seafood, fish, shrimp, grilling, cooking, cookout, barbecue, barbeque, bbq"
